version: "3"
services:
  nginx:
    container_name: beowulf-nginx
    image: nginx:latest
    working_dir: /usr/share/nginx/html
    tty: true # keep container alive without default command
    ports:
      - "80:80"
    volumes: ["./nginx:/etc/nginx/conf.d"]
    depends_on:
      - prisma
      - mysql
      - yoga
    networks:
      - beowulf
  prisma:
    container_name: beowulf-prisma
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: ${MYSQL_USER}
            password: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - beowulf
  mysql:
    container_name: beowulf-mysql
    image: mysql:5.7
    restart: always
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - beowulf
  yoga:
    container_name: beowulf-yoga
    image: node:latest
    working_dir: /usr/src/app
    tty: true # keep container alive without default command
    ports:
      - "4000:4000"
    volumes: ["./:/usr/src/app", "node_modules:/usr/src/app/node_modules"]
    env_file: .env
    networks:
      - beowulf
volumes:
  mysql: ~
  node_modules:
networks:
  beowulf:
